// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYty8TA37l9ZfjD7F1zf_1UgOOAdlHhyI',
    appId: '1:662080486637:web:50dbdbdcde6825174120e4',
    messagingSenderId: '662080486637',
    projectId: 'siremo-project',
    authDomain: 'siremo-project.firebaseapp.com',
    storageBucket: 'siremo-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcBeAw6vplvhrFaord6yfyiyVUCkPH1NU',
    appId: '1:662080486637:android:be83a19ba90a2b654120e4',
    messagingSenderId: '662080486637',
    projectId: 'siremo-project',
    storageBucket: 'siremo-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCE6fR-XilSZZrjYSPOmbmG9796xJhexww',
    appId: '1:662080486637:ios:a2e6cb5fe6bd7d024120e4',
    messagingSenderId: '662080486637',
    projectId: 'siremo-project',
    storageBucket: 'siremo-project.firebasestorage.app',
    iosBundleId: 'com.example.siremoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCE6fR-XilSZZrjYSPOmbmG9796xJhexww',
    appId: '1:662080486637:ios:a2e6cb5fe6bd7d024120e4',
    messagingSenderId: '662080486637',
    projectId: 'siremo-project',
    storageBucket: 'siremo-project.firebasestorage.app',
    iosBundleId: 'com.example.siremoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYty8TA37l9ZfjD7F1zf_1UgOOAdlHhyI',
    appId: '1:662080486637:web:5b4126758babdf484120e4',
    messagingSenderId: '662080486637',
    projectId: 'siremo-project',
    authDomain: 'siremo-project.firebaseapp.com',
    storageBucket: 'siremo-project.firebasestorage.app',
  );
}
